### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Varikap** [Varikap/POP-SF49-16#1]
- [ ] - Za Akciju i TipNamestaja  unesi izmeni obrisi prikazi
- [ ] - Dovrsiti Projekat.cs
- [ ] - Napraviti login koristeci Projekat.cs
- [ ] - Primer: Napravi za namestaj da ne cuva ceo tip_namestaja nego samo njegov id
- [ ] - Odradi do while sve
